version: '3.7'
services:
  db:
    image: postgres:14
    container_name: booking_postgres
    env_file:
      - .env-non-dev
    ports:
      - '5432:5432'

  redis:
    image: redis:7
    container_name: booking_redis

  booking:
    build:
      context: .
    container_name: booking_app
    env_file:
      - .env-non-dev
    command: ["/booking/docker/app.sh"]
    ports:
      - '9000:8000'
    depends_on:
      - db
      - redis

  celery:
    build:
      context: .
    container_name: booking_celery
    command: ["/booking/docker/celery.sh", "celery"]
    env_file:
      - .env-non-dev
    depends_on:
      - booking

  flower:
    build:
      context: .
    container_name: booking_flower
    command: ["/booking/docker/celery.sh", "flower"]
    env_file:
      - .env-non-dev
    ports:
      - '5555:5555'
    depends_on:
      - celery